### ISSUE TITLE
Can you close the screenmelting procces by alt-f4?

### ISSUE THREAD

**Issue by icofs223** [weyh/screen-melter#1]
I have some concerns about this program. Does it disable taskmanager? Does it have any pre-set arguments? Can you close it with ALT-F4? Is it destructive?

**Comment by dogemc8854** [comment]
I should test it on a vm...

**Comment by dogemc8854** [comment]
it gives off entry point not found

**Comment by weyh** [comment]
By default no user input is disabled. With the args mentioned in the README.md file you can partially disable the keyboard and mouse.
No destructive file operations are made.

**Comment by icofs223** [comment]
So you can close the melting procces by altf4?

**Comment by weyh** [comment]
If disable_input or disable_keyboard flags are not set it should work.

(The code is poorly optimized so it might be a bit hard to kill the process on a weaker hardware.)

**Comment by icofs223** [comment]
never mind, I found a way to close it by task mgr
