### ISSUE TITLE
Exe not found

### ISSUE THREAD

**Issue by TheRealReed** [weyh/screen-melter#2]
I can't find the exe file in the folder.
so, then I can't run the cmd command that uses a exe.
`screen-melter.exe -B "-t 2000 --exit_time=10000"`
!I am new to github so i dont know how to close a issue but i found the issue!

**Comment by weyh** [comment]
Hi, you probably downloaded the repo. It's not advised to store blob files in version control, so you can access them in the release tab. 

![image](https://github.com/weyh/screen-melter/assets/16374863/4b2027a4-8e96-4e3f-b68d-08a4f392a4c7)

The zip file listed there contains the exe.

**Comment by TheRealReed** [comment]
oh yeah i found the issue but i dont know how to close issues
but thanks
