### ISSUE TITLE
Not working on Win11

### ISSUE THREAD

**Issue by MaybeAnge** [weyh/screen-melter#3]
Not working on Win11....
Nothing just happens when you launch it.

**Comment by weyh** [comment]
@MaybeAnge can you specify the problematic windows 11 version?

**Comment by MaybeAnge** [comment]
Edition	Windows 11 Pro
Version	23H2
Installed on	‎1/‎23/‎2024
OS build	22631.4541
Experience	Windows Feature Experience Pack 1000.22700.1055.0

**Comment by MaybeAnge** [comment]
But, I recreated mine so my version of the Melter works, take example if you want to patch yours: https://github.com/MaybeAnge/Risitas-18-25-Twitch-Booster/blob/main/resources/files/WindowsMelter/WindowsMelter/WindowsMelter.cpp

**Comment by weyh** [comment]
Then I'll close it
